# Permalinks
permalink:        pretty

# Setup
title:            mschubert.github.io
#tagline:          'A Jekyll theme'
description:      'Page to collect and organise different ideas. Expect random musings and code snippets.'
url:              http://mschubert.github.io
baseurl:          /

author:
  name:           'Michael Schubert'
  url:            https://twitter.com/_ms03

paginate:         5
